### ISSUE TITLE
Display past conferences in reverse order ?

### ISSUE THREAD

**Issue by manusajith** [ruby-conferences/ruby-conferences.github.io#104]
It might be useful to display the past conferences in reverse order(most recently over at first) ?

**Comment by jonallured** [comment]
I just looked and there are now 129 events on the past list, so I agree there might be a better way to handle this page. @camerond do you have any ideas about how this could be improved? Reversing the order might help, but maybe there's something else that could be done.

Maybe some sort of year navigation?

**Comment by adamniedzielski** [comment]
We could keep the YAML file as it is and reverse the list when rendering the site. Grouping the list by year by introducing headings for each year would also be nice.
