### ISSUE TITLE
Do not check if past links are reachable

### ISSUE THREAD

**Issue by adamniedzielski** [ruby-conferences/ruby-conferences.github.io#117]
As seen in https://travis-ci.org/ruby-conferences/ruby-conferences.github.io/builds/186652803

It doesn't make sense to check links for past events, because the website may be no longer maintained.

**Comment by jonallured** [comment]
Hey @adamniedzielski, I see what you mean, but it's often handy to get back to the site and the completionist in me has a hard time removing accurate data from the site. Most of these sites are maintained so I'd like to keep the data.

An idea I had recently was to use the [new Travis Crons feature][cron] to build the site nightly. It would definitely been nice to know about these broken links before they fail a PR.

Anyway, I'm not sure what I'm going to do about it, but know that it's been bothering me too! 😄 

[cron]: https://blog.travis-ci.com/2016-12-06-the-crons-are-here

**Comment by jonallured** [comment]
True, true, but I'd like to know when/if those links break. The thing that sucks is that htmlproofer is sometimes wrong about those links being broken. Like on #118 there are three errors but then when I go to actually try those links in my browser, they work. It's like one build will be fine but then another build results in those links being reported as errors.

**Comment by jonallured** [comment]
With 5ba976f88cc568431e7dba07b8a6abc984ccd4c5 I've moved the htmlproofer verification step to the end. I'd still like to go further and improve things on this front, but this was an easy improvement to make.

**Comment by jonallured** [comment]
My latest attempt to make htmlproofer feedback relevant is #203 - I'm only checking those links when the daily Travis job runs. Going to close this for now with that change and see what I think of it.
