### ISSUE TITLE
Timezones for CFP closing dates

### ISSUE THREAD

**Issue by mermop** [ruby-conferences/ruby-conferences.github.io#163]
I'm not *entirely* certain that this is a problem, but I'd like to check.

Here in New Zealand we're almost a day ahead of some parts of the world that contain a lot of Ruby programmers, so the timezone of dates is quite important. The CFP for Kiwi Ruby closes at midnight the night of on Monday 3rd July in NZ time, which is 2 in the morning of that day in Hawaii, 5am in LA, and 8am in New York. If we'd chosen to close the CFP at 9pm, it'd still be Sunday in Hawaii.

This means that the behaviour around turning the dates into "tomorrow" etc based on local time zone with Moment can lead to misleading outcomes, if I've interpreted the way it's working [here](https://github.com/ruby-conferences/ruby-conferences.github.io/blob/e94be6ae114be4ba37c1f6b5f6588eaa3a21de70/js/behavior.js#L15) correctly. So someone in Hawaii looking at the website at 9pm Monday NZ time would still see "CFP closes tomorrow", even though it would be closing in three hours. And on the flipside, NZ viewers would often be told CFPs were closed when they weren't.

I'm not sure what the answer to this is - I guess requiring timezones and datetimes somehow in the data input? 

Thanks!

**Comment by jonallured** [comment]
Hey @mermop, thanks for opening the issue! If there is a problem, I would certainly be interested in working on a way to fix it, but to be honest, I can't tell! I read through the Moment docs again today and I think it's ok, but I couldn't think of a good way to be sure. Have you seen something that looked wrong?

**Comment by jonallured** [comment]
Going to close this for now - let me know if you have any further thoughts!
