### ISSUE TITLE
Past conferences showing in current list

### ISSUE THREAD

**Issue by eshaiju** [ruby-conferences/ruby-conferences.github.io#195]
In website still showing past conference. Is this a bug?. can we fix it?
![screen shot 2017-10-17 at 4 23 04 pm](https://user-images.githubusercontent.com/2918256/31661272-b8ed99ee-b357-11e7-912c-b68a919755e0.png)

**Comment by eshaiju** [comment]
Added pr #196

**Comment by jonallured** [comment]
Thanks!!
