### ISSUE TITLE
Add RSS Feed to site

### ISSUE THREAD

**Issue by zoras** [ruby-conferences/ruby-conferences.github.io#226]
This will allow new additions to be tweeted automatically or open other possibilities like sending out emails notifications to subscribers, IFTTT etc.

**Comment by jonallured** [comment]
I did have an RSS feed of the site at one point, but it was a hassle to keep up-to-date, so I just stopped doing it and this issue you have opened is the first time anyone has brought it up, haha. I'm intrigued by your ideas around sending email notification and automated tweets - how would you do those things with the feed?

**Comment by zoras** [comment]
I think these might work.

Feed generation can be automated with:
* RSS - https://github.com/snaptortoise/jekyll-rss-feeds
* Atom - https://github.com/jekyll/jekyll-feed

Automated tweets
* https://ifttt.com/applets/ELCMuz4H-automatically-tweet-updates-from-pew-research
* https://ifttt.com/applets/RKdiSRZ4-rss-feed-autoposts-to-twitter-and-facebook-pages

Email notifications
* https://blog.mailchimp.com/tag/rss-to-email/
* https://ifttt.com/applets/YnbGBZDy-send-email-rss

Others:
* https://ifttt.com/feed

**Comment by paneq** [comment]
Also, Slack can integrate with RSS to notify about new conferences. Right now I am watching this repository to achieve that knowledge.

**Comment by geraldb** [comment]
FYI: The (alternative) ruby conferences & camps calendar page has a web feed in rss [1] and json [2] too, see <http://planetruby.github.io/calendar/2018.html>. It's also built from a datafile with jekyll (and believe it or not - it has more github stars too). Just in case you need some inspiration on how to do it. Copy as you please, it's all public domain. Cheers. Prost.

PS: If anyone thinks about sharing datafiles - yes, yes, of course. I suggest opening (and discussing) in a new ticket / issue.

[1]: http://planetruby.github.io/calendar/feed.xml
[2]: http://planetruby.github.io/calendar/feed.json

**Comment by pjmartorell** [comment]
yes, I think it would be a good feature. I would like to create a Zap to automatically create events in my calendar and at least I would need a JSON or RSS

**Comment by bogn83** [comment]
There's a pull request for this now at https://github.com/ruby-conferences/ruby-conferences.github.io/pull/339. Maybe you should add a thumbs up over there.

If you know how to automate adding a yml key to a changed block in Travis or GH Actions you should chime in there. Or if you are knowledgeable in editing a Dangerfile you could help out as well. Details over there.

**Comment by siaw23** [comment]
I'm scraping and creating a JSON of events here if anyone is interested https://ruby-events-api.onrender.com/api/v1/events. 

https://github.com/siaw23/ruby_events_api :)

**Comment by adarsh** [comment]
I feel like this is covered by #492 now?

**Comment by ivoanjo** [comment]
My 0.01c is that having an rss feed would still be cool, because e.g. I can know about new conferences and when I can submit to them.

**Comment by adarsh** [comment]
This is challenging because our database (such as it is), is really a list of events in order, like a calendar. Each entry doesn't have a "created_at" timestamp so I don't really know how a date sequential RSS feed would work, although I'm not an expert on the format.

**Comment by jonallured** [comment]
Way back when I had a feed in the sense that I would make posts and the feed was those. So I'd update the list of events and then ALSO make a quick post with that same sorta info. It was a pain so I stopped doing it. 🤷
