### ISSUE TITLE
Enable TLS on the site using Let's Encrypt

### ISSUE THREAD

**Issue by sikachu** [ruby-conferences/ruby-conferences.github.io#258]
Thank you very much for your work on keeping this updated.

GitHub [recently introduced](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) support for TLS certificate for GitHub Pages. I think we should enable this if it's not much of a hassle.

It looks like we need to update `A` record to point to new IP addresses [as described here](https://help.github.com/articles/setting-up-an-apex-domain/), then optionally we can enforce HTTPS connection in repository config.

What do you think?

**Comment by sikachu** [comment]
The site is now accessible via HTTPS!

However, It looks like we're running into mixed content error/warning, so I submitted #259 to fix this.

**Comment by jonallured** [comment]
Closed with #259
