### ISSUE TITLE
Caching disables the conferences list auto update

### ISSUE THREAD

**Issue by amrabdelwahab** [ruby-conferences/ruby-conferences.github.io#329]
In the past, past and upcoming lists were static so the data displayed only changed on deployment. That's why it made sense to only invalidate the cache on deployment.

However, at the moment we need a mechanism to invalidate the CDN cache every morning to automatically upgrade what shows up in the list

**Comment by jonallured** [comment]
Oh wow, I didn't even think of this! I guess a solution that could work is using CircleCI's scheduling capabilities:

https://circleci.com/docs/2.0/configuration-reference/#schedule

Although that would slightly change how things are deployed. I'll keep thinking about this, but thanks for pointing it out!! ❤️

**Comment by amrabdelwahab** [comment]
If you need a second pair of eyes on this let me know, what is your current setup looking like, what do you use for caching and so on

**Comment by Morozzzko** [comment]
Is there any progress on that? Could we turn it into an "help wanted" kind of issue?

**Comment by adarsh** [comment]
Bump.

**Comment by adarsh** [comment]
I believe this is no longer an issue as we are deploying on GitHub Pages, who handle CDN for us. 

Other maintainers: re-open if I got this wrong.
