### ISSUE TITLE
Let's Work Together - Invite to Join Planet Ruby - A Modest Proposal for 2023

### ISSUE THREAD

**Issue by geraldb** [ruby-conferences/ruby-conferences.github.io#409]
Hello,
   Happy new year! Prosit 2022!  First thanks for the fantastic ruby conferences page / website.  

   I'm the humble maintainer of the planet ruby and the ruby conferences page over there. See for the source <https://github.com/planetruby/conferences> and <https://planetruby.github.io/conferences/> for the published / live pages. 

If I dare to say (and speculate that maintenance has become a thankless job) - you have open pull request (5) and issues (4) and there hasn't been any update to the website (e.g. no web feed, no COVID-19 updates, etc.), thus, may I suggest joining forces over at the Planet Ruby. You are welcome anytime and I can promise you that all data in the [conferences.yml](https://github.com/ruby-conferences/ruby-conferences.github.io/blob/master/_data/conferences.yml) will get merged in so nothing gets lost (as far as I can tell only the video_link is missing in the Planet Ruby datafiles that are organized by year, see <https://github.com/planetruby/conferences/tree/master/_data>.

   Anyways, let me know what you think. Keep it up. Cheers. Prosit 2022!

PS:

You will also get a big thank you on the page and 
get honored as the founder of the ruby conferences page.

See as an example the book collection at Planet Ruby
started / founded by Florent Guilleux  in 2016 - <https://github.com/planetruby/books>.

PPS: Updated for 2022. One year without a response or even a comment. Let's see what 2022 brings.

PPPS: Just checking in ;-). Happy new year 2023! Prosit. Anyone cares to comment.

**Comment by adarsh** [comment]
We now have extra maintainers and a plan for support from Ruby Central. At this time, I'm not sure a merger makes sense. If another maintainer disagrees, they can re-open this issue.
