### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by jonallured** [ruby-conferences/ruby-conferences.github.io#512]
I've lost some enthusiasm for this project and so I'm opening up this issue in the hopes that I can find people that are interested in working on it. I've heard from a few people over the years that were interested in helping such as @marcoroth @andycroll @adarsh but probably more that I'm forgetting.

I don't want to give the project away completely but I do want to have help in merging PRs, improving the site and just generally not being the only person to lead this thing.

So I think what I'm saying is that if you want to have more input on this project then please respond to this issue and let's work something out!

**Comment by adarsh** [comment]
@jonallured Totally understandable. This project is extremely valuable and I appreciate your work on it in service to our community.

I'd be happy to be a maintainer of the project. We may also be able to find some funding at Ruby Central to redesign the site, augment with features, etc. but until then I'm a whiz at merging low-volume PRs and stale issues :)

**Comment by andycroll** [comment]
@jonallured Also happy to be involved.

**Comment by jonallured** [comment]
ok going to add y'all to the project 👍

**Comment by marcoroth** [comment]
Same here, more than happy to help maintain the project and to help keep evolving it.

**Comment by adarsh** [comment]
+3 maintainers. I feel pretty comfortable this is in good hands at this point.
