### ISSUE TITLE
Split data file into sub-files by year

### ISSUE THREAD

**Issue by adarsh** [ruby-conferences/ruby-conferences.github.io#515]
As per conversation in #487 :

The data file is very long. 

> I almost wonder if it's easier to have sub-files also, maybe aggregated per year? Not for this PR but maybe consider for the future.

**Comment by marcoroth** [comment]
Closing this with the same reason as in https://github.com/ruby-conferences/ruby-conferences.github.io/pull/672#issuecomment-2424357830
