### ISSUE TITLE
Migrate git branch from `master` to `main`

### ISSUE THREAD

**Issue by marcoroth** [ruby-conferences/ruby-conferences.github.io#516]
Most repositories have migrated to the new `main` git default. I was wondering if we should do the same here.

I was reluctant to just to do it because I don't know if it would affect deployments or the like, which is why I open this issue so we can discuss it.

**Comment by adarsh** [comment]
I was going to open the same issue. I am in favor of main.

**Comment by adarsh** [comment]
Seems like we may not be able to do this as of now, due to GH Pages:

https://github.com/orgs/community/discussions/23147

**Comment by marcoroth** [comment]
Oh interesting. I'm actually wondering if this is still the case. Quite some time has passed now 🤔

**Comment by adarsh** [comment]
I did very little research. Worth another set of eyes.

**Comment by Morozzzko** [comment]
![image](https://github.com/ruby-conferences/ruby-conferences.github.io/assets/887264/487e2a6a-2254-466d-9294-120dbf09b36c)

Should be fine. That's a screenshot from my own Jekyll blog/repo. Repo -> Settings -> Pages

**Comment by adarsh** [comment]
Ok I followed [these tips][1] and looks like it seems ok. I have not deleted `master` yet, out of caution. I did update GH Pages to deploy from `main`. 🤞🏾 

LMK if it looks ok for others. 

[1]: https://gist.github.com/jonlabelle/81206faafb56714d7499efa54eb8f3ff

**Comment by marcoroth** [comment]
I think this looks good. Seems like the site deployed successfully and the changes from #520 are up. 

#520 was also the last pull request pointing to `master`.

**Comment by marcoroth** [comment]
Closing this, as I think everything seems to working well on `main` now! 🙌🏼
