### ISSUE TITLE
Separate CFP .ical feed

### ISSUE THREAD

**Issue by adarsh** [ruby-conferences/ruby-conferences.github.io#581]
I am a big fan of the iCal feed added [here](https://github.com/ruby-conferences/ruby-conferences.github.io/commit/e094726d3f4be3e78d88b2b0b36a5b963d31423d). I'm a conference organizer and it's helpful for me to try to plan to attend other conferences.

I like the idea of having CFP dates also, [as implemented here](https://github.com/ruby-conferences/ruby-conferences.github.io/commit/ff7b6131d936622220ab43da74584b5037059b25), but for me personally, it has added a ton of noise to my daily calendar.

![image](https://github.com/ruby-conferences/ruby-conferences.github.io/assets/913757/796fa431-c73d-4ff5-88a7-a70fdb241ed7)

Is anyone else feeling this? I wanted to check before I proposed a solution like "add a separate conference dates + CFP ical feed".

**Comment by marcoroth** [comment]
I proceeded to merge #576 to see how it goes and feels, but I'd more than happy to create a separate feed for it 👍🏼
