### ISSUE TITLE
Follow up on new PhRUG meetup for July 31

### ISSUE THREAD

**Issue by westoque** [ruby-conferences/ruby-conferences.github.io#691]
Hi Marco,

Per @graial, I'm creating a new issue pointing to:

https://github.com/ruby-conferences/ruby-conferences.github.io/pull/643#issuecomment-2254166018

A PR has been created in the comment above to reflect an event for 07-31-2024 but might not have been visible.

Thanks

**Comment by marcoroth** [comment]
Hey @westoque, thanks for pointing to it! I'm currently without my notebook too, but can merge. Would you mind opening a pull request for it? Thank you!

**Comment by westoque** [comment]
@marcoroth added PR https://github.com/ruby-conferences/ruby-conferences.github.io/pull/692

thank you.
