### ISSUE TITLE
RSS Injestion?

### ISSUE THREAD

**Issue by crespire** [ruby-conferences/ruby-conferences.github.io#711]
Does the site offer a way to ingest events via RSS? I know I can get an RSS feed from the site, but I've set up Toronto Ruby's site to be able to render an RSS feed, and it would be good to be able to hook that up here for automated publishing.

I recall discussing this in passing on a previous issue, but I can't seem to find it now!

**Comment by marcoroth** [comment]
Hey @crespire, there is nothing as of right now, but I'd love to make that work! I started working on automating things a few times, but never really got anywhere

**Comment by crespire** [comment]
If you need a hand, I'd love to help!

**Comment by marcoroth** [comment]
I think the tricky part is to write the the right thing to the YAML file and checking if the event doesn't exist already. If you want to take a stab I'd love to see what you could come up with.

**Comment by crespire** [comment]
Yes, I can see if i can take a stab. Curious if you have any approaches in mind? I have not worked with Liquid/Jekyll like this before so any tips appreciated!

**Comment by marcoroth** [comment]
I think I would want to make this Jeykll-independent. I was thinking of a GitHub Action that runs via CRON and just openes PRs (or commits it directly) by changing/appending to the `meetups.yml`.

**Comment by marcoroth** [comment]
I saw a project/video a few years ago where they used the GitHub Repo as the datastore and automated the updates using GitHub Actions.

I'm not 100% sure but I think it was https://githubnext.com/projects/flat-data, maybe that could also work here!

**Comment by crespire** [comment]
Perfect, I'll take a look!

**Comment by marcoroth** [comment]
@crespire just wanted to mention that I opened #720 which adds an automation for the Meetup.com events, maybe we can easily adapt it to also make it work for RSS.

**Comment by marcoroth** [comment]
I think I just realized that RSS doesn't make sense for this. 

It doesn't have standard fields for `date`, `start_time` and `end_time` unless you use non-standard fields or reuse the `published`, `updated`, `dc:date` timestamps, but that seems less than ideal.

I have a working RSS feed for the [seattlerb.org](https://seattlerb.org) website, but like I said, it doesn't quite work - at least not for the use-case of feeding it automatically into [ubyconferences.org](https://rubyconferences.org).

Here's the RSS feed for reference: https://github.com/marcoroth/seattlerb.org/commit/a3d17858da0c29460fe1433a7ce89970a8dc87d3

**Comment by crespire** [comment]
Hey Marco, no problem. Would JSON work? I just have to build the appropriate endpoint for Toronto Ruby, so maybe I can take a look at how Meetup does it and do something similar on the provider side.

**Comment by marcoroth** [comment]
Yeah, I think either would work, modelling it the same way as the meetup API might be a little bit too excessive, but technically that could work too. 

But the ical could be used by attendees of the meetup as well, so there's that benefit too.

**Comment by marcoroth** [comment]
For completeness: I'm going to link to the PR over on the toronto-ruby.com repo: https://github.com/toronto-ruby/toronto-ruby.com/pull/42 and the pull request here:  https://github.com/ruby-conferences/ruby-conferences.github.io/pull/735

**Comment by crespire** [comment]
@marcoroth ended up implementing an ICS method which completes this integration request though not via RSS.
