### ISSUE TITLE
Will the new meetup github action catch changes as well?

### ISSUE THREAD

**Issue by nhessler** [ruby-conferences/ruby-conferences.github.io#724]
I'm curious if changed meetup titles will be caught in the new automation. No worries if not. I can submit manual changes as well.

but, for context, I don't often know the speaker and title well in advance so I have a placeholder to meet the expectations of our venue and add the speaker, talk, and details once I know what they are. this is also why I've been submitting monthly PRs. regardless love that this automation exists and thank you getting it going!

**Comment by marcoroth** [comment]
Yeah good point! TL;DR: not yet.

I was working on that, but it's trickier to update the existing YAML file compared to just appending new entries, which is why that's missing right now. But this is up next!

**Comment by marcoroth** [comment]
Resolved via https://github.com/ruby-conferences/ruby-conferences.github.io/pull/727

**Comment by nhessler** [comment]
wow! that's awesome! thanks!
