### ISSUE TITLE
meetup page showing old listings

### ISSUE THREAD

**Issue by adriangohjw** [ruby-conferences/ruby-conferences.github.io#740]
havne't dug very deep but currently the website shows past meetups
however when i git clone it, it doesn't show up on my local environment 
 
<img width="1358" alt="Screenshot 2024-08-31 at 3 11 24 AM" src="https://github.com/user-attachments/assets/1f83f3b5-0f4b-4ed2-bb46-25f17ee5709e">

**Comment by marcoroth** [comment]
Hey @adriangohjw, thanks for reporting!

I'm not quite sure why that's the case. I think it has to do with the fact that it's a static website. So, if it doesn't get redeployed everyday it can't "remove" the past events automatically. I feel like it didn't happen in the past, but maybe we just deployed enough so it wasn't really noticeable.

I guess there would be two solutions to this problem:
- Setup an automation that builds and deploys the site daily
- Add some JavaScript logic, that evaluates on the client and compares the current date with the meetup/conf date and removes itself if the date in the past. We do something similar for the red "callout-texts" here: https://github.com/ruby-conferences/ruby-conferences.github.io/blob/5bb083f379e52e7eeb6a740f961e40ea8ba8fa23/js/behavior.js#L29

**Comment by adriangohjw** [comment]
took a closer look, and you were correct—site.data.meetups is loaded at build time rather than on page load.

Since this site is hosted on GitHub Pages, I’ll create a quick PR to implement a daily cron job for redeployment. This will ensure that all parts of the platform using `site.data...` maintain a single source of truth across different pages.
