### ISSUE TITLE
Add RubyConf Philippines 2017

### ISSUE THREAD

**Issue by adamniedzielski** [ruby-conferences/ruby-conferences.github.io#97]
Please refer to http://rubyconf.ph/

**Comment by jonallured** [comment]
Hey @adamniedzielski, thanks for the heads up! In the future, don't be bashful about opening a PR - I love contributions!! :D

**Comment by adamniedzielski** [comment]
I'm not shy, I was just lazy 😄 Sorry for that!

**Comment by jonallured** [comment]
Haha, no problem 😸
